/**
 * Open Service Broker API
 * The Open Service Broker API defines an HTTP(S) interface between Platforms and Service Brokers.
 *
 * OpenAPI spec version: master - might contain changes that are not yet released
 * Contact: open-service-broker-api@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 */

package io.swagger.server.model

case class Service(
  name: String,
    id: String,
    description: String,
    tags: Option[List[String]],
    requires: Option[List[String]],
    bindable: Boolean,
    instances_retrievable: Option[Boolean],
    bindings_retrievable: Option[Boolean],
    allow_context_updates: Option[Boolean],
    metadata: Option[Metadata],
    dashboard_client: Option[DashboardClient],
    binding_rotatable: Option[Boolean],
    plan_updateable: Option[Boolean],
    plans: List[Plan]
  )
