/**
 * Open Service Broker API
 * The Open Service Broker API defines an HTTP(S) interface between Platforms and Service Brokers.
 *
 * OpenAPI spec version: master - might contain changes that are not yet released
 * Contact: open-service-broker-api@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 */

package io.swagger.server.model

case class ServiceInstanceResource(
  service_id: Option[String],
    plan_id: Option[String],
    dashboard_url: Option[String],
    parameters: Option[Object],
    maintenance_info: Option[MaintenanceInfo],
    metadata: Option[ServiceInstanceMetadata]
  )
