/**
 * Open Service Broker API
 * The Open Service Broker API defines an HTTP(S) interface between Platforms and Service Brokers.
 *
 * OpenAPI spec version: master - might contain changes that are not yet released
 * Contact: open-service-broker-api@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 */


package io.swagger.server.api

import io.swagger.server.model.AsyncOperation
import io.swagger.server.model.Error
import io.swagger.server.model.LastOperationResource
import io.swagger.server.model.ServiceBindingRequest
import io.swagger.server.model.ServiceBindingResource
import io.swagger.server.model.ServiceBindingResponse

import java.io.File

import org.scalatra.ScalatraServlet
import org.scalatra.swagger._
import org.json4s._
import org.json4s.JsonDSL._
import org.scalatra.json.{ JValueResult, JacksonJsonSupport }
import org.scalatra.servlet.{ FileUploadSupport, MultipartConfig, SizeConstraintExceededException }

import scala.collection.JavaConverters._

class ServiceBindingsApi(implicit val swagger: Swagger) extends ScalatraServlet
  with FileUploadSupport
  with JacksonJsonSupport
  with SwaggerSupport {
  protected implicit val jsonFormats: Formats = DefaultFormats

  protected val applicationDescription: String = "ServiceBindingsApi"

  before() {
    contentType = formats("json")
    response.headers += ("Access-Control-Allow-Origin" -> "*")
  }
  

  val serviceBinding.bindingOperation = (apiOperation[ServiceBindingResponse]("serviceBinding.binding")
      summary "generation of a service binding"
      parameters(headerParam[String]("xBrokerAPIVersion").description(""), pathParam[String]("instanceId").description(""), pathParam[String]("bindingId").description(""), bodyParam[ServiceBindingRequest]("body").description(""), headerParam[String]("xBrokerAPIOriginatingIdentity").description("").optional, headerParam[String]("xBrokerAPIRequestIdentity").description("").optional, queryParam[Boolean]("acceptsIncomplete").description("").optional)
  )

  put("/v2/service_instances/:instance_id/service_bindings/:binding_id",operation(serviceBinding.bindingOperation)) {
    
    
          val xBrokerAPIVersion = request.getHeader("xBrokerAPIVersion")

    println("xBrokerAPIVersion: " + xBrokerAPIVersion)
    
    
      val instanceId = params.getOrElse("instanceId", halt(400))
    
    println("instanceId: " + instanceId)
    
    
      val bindingId = params.getOrElse("bindingId", halt(400))
    
    println("bindingId: " + bindingId)
    
    
          val body = parsedBody.extract[ServiceBindingRequest]

    println("body: " + body)
    
    
          val xBrokerAPIOriginatingIdentity = request.getHeader("xBrokerAPIOriginatingIdentity")

    println("xBrokerAPIOriginatingIdentity: " + xBrokerAPIOriginatingIdentity)
    
    
          val xBrokerAPIRequestIdentity = request.getHeader("xBrokerAPIRequestIdentity")

    println("xBrokerAPIRequestIdentity: " + xBrokerAPIRequestIdentity)
    
    
                val acceptsIncomplete = params.getAs[Boolean]("acceptsIncomplete")

    println("acceptsIncomplete: " + acceptsIncomplete)
  }

  

  val serviceBinding.getOperation = (apiOperation[ServiceBindingResource]("serviceBinding.get")
      summary "gets a service binding"
      parameters(headerParam[String]("xBrokerAPIVersion").description(""), pathParam[String]("instanceId").description(""), pathParam[String]("bindingId").description(""), headerParam[String]("xBrokerAPIOriginatingIdentity").description("").optional, headerParam[String]("xBrokerAPIRequestIdentity").description("").optional, queryParam[String]("serviceId").description("").optional, queryParam[String]("planId").description("").optional)
  )

  get("/v2/service_instances/:instance_id/service_bindings/:binding_id",operation(serviceBinding.getOperation)) {
    
    
          val xBrokerAPIVersion = request.getHeader("xBrokerAPIVersion")

    println("xBrokerAPIVersion: " + xBrokerAPIVersion)
    
    
      val instanceId = params.getOrElse("instanceId", halt(400))
    
    println("instanceId: " + instanceId)
    
    
      val bindingId = params.getOrElse("bindingId", halt(400))
    
    println("bindingId: " + bindingId)
    
    
          val xBrokerAPIOriginatingIdentity = request.getHeader("xBrokerAPIOriginatingIdentity")

    println("xBrokerAPIOriginatingIdentity: " + xBrokerAPIOriginatingIdentity)
    
    
          val xBrokerAPIRequestIdentity = request.getHeader("xBrokerAPIRequestIdentity")

    println("xBrokerAPIRequestIdentity: " + xBrokerAPIRequestIdentity)
    
    
                val serviceId = params.getAs[String]("serviceId")

    println("serviceId: " + serviceId)
    
    
                val planId = params.getAs[String]("planId")

    println("planId: " + planId)
  }

  

  val serviceBinding.lastOperation.getOperation = (apiOperation[LastOperationResource]("serviceBinding.lastOperation.get")
      summary "last requested operation state for service binding"
      parameters(headerParam[String]("xBrokerAPIVersion").description(""), pathParam[String]("instanceId").description(""), pathParam[String]("bindingId").description(""), headerParam[String]("xBrokerAPIOriginatingIdentity").description("").optional, headerParam[String]("xBrokerAPIRequestIdentity").description("").optional, queryParam[String]("serviceId").description("").optional, queryParam[String]("planId").description("").optional, queryParam[String]("operation").description("").optional)
  )

  get("/v2/service_instances/:instance_id/service_bindings/:binding_id/last_operation",operation(serviceBinding.lastOperation.getOperation)) {
    
    
          val xBrokerAPIVersion = request.getHeader("xBrokerAPIVersion")

    println("xBrokerAPIVersion: " + xBrokerAPIVersion)
    
    
      val instanceId = params.getOrElse("instanceId", halt(400))
    
    println("instanceId: " + instanceId)
    
    
      val bindingId = params.getOrElse("bindingId", halt(400))
    
    println("bindingId: " + bindingId)
    
    
          val xBrokerAPIOriginatingIdentity = request.getHeader("xBrokerAPIOriginatingIdentity")

    println("xBrokerAPIOriginatingIdentity: " + xBrokerAPIOriginatingIdentity)
    
    
          val xBrokerAPIRequestIdentity = request.getHeader("xBrokerAPIRequestIdentity")

    println("xBrokerAPIRequestIdentity: " + xBrokerAPIRequestIdentity)
    
    
                val serviceId = params.getAs[String]("serviceId")

    println("serviceId: " + serviceId)
    
    
                val planId = params.getAs[String]("planId")

    println("planId: " + planId)
    
    
                val operation = params.getAs[String]("operation")

    println("operation: " + operation)
  }

  

  val serviceBinding.unbindingOperation = (apiOperation[Object]("serviceBinding.unbinding")
      summary "deprovision of a service binding"
      parameters(headerParam[String]("xBrokerAPIVersion").description(""), pathParam[String]("instanceId").description(""), pathParam[String]("bindingId").description(""), queryParam[String]("serviceId").description(""), queryParam[String]("planId").description(""), headerParam[String]("xBrokerAPIOriginatingIdentity").description("").optional, headerParam[String]("xBrokerAPIRequestIdentity").description("").optional, queryParam[Boolean]("acceptsIncomplete").description("").optional)
  )

  delete("/v2/service_instances/:instance_id/service_bindings/:binding_id",operation(serviceBinding.unbindingOperation)) {
    
    
          val xBrokerAPIVersion = request.getHeader("xBrokerAPIVersion")

    println("xBrokerAPIVersion: " + xBrokerAPIVersion)
    
    
      val instanceId = params.getOrElse("instanceId", halt(400))
    
    println("instanceId: " + instanceId)
    
    
      val bindingId = params.getOrElse("bindingId", halt(400))
    
    println("bindingId: " + bindingId)
    
    
                val serviceId = params.getAs[String]("serviceId")

    println("serviceId: " + serviceId)
    
    
                val planId = params.getAs[String]("planId")

    println("planId: " + planId)
    
    
          val xBrokerAPIOriginatingIdentity = request.getHeader("xBrokerAPIOriginatingIdentity")

    println("xBrokerAPIOriginatingIdentity: " + xBrokerAPIOriginatingIdentity)
    
    
          val xBrokerAPIRequestIdentity = request.getHeader("xBrokerAPIRequestIdentity")

    println("xBrokerAPIRequestIdentity: " + xBrokerAPIRequestIdentity)
    
    
                val acceptsIncomplete = params.getAs[Boolean]("acceptsIncomplete")

    println("acceptsIncomplete: " + acceptsIncomplete)
  }

}
